DB_HOST: "localhost"
DB_PORT: 3306
DB_USER: "root"
DB_PASS: ""
DB_NAME: "sanmateo"
CRYPT_KEY: "vz7oWXaUm691nvAwXJuvs9U6UM04ZZs0"
TOKEN_KEY: "XvkAKPFg6vHQ930PRt13REOZjJuAu0b9fbLaqXC8"
PUSHER_APP_ID: "220781"
PUSHER_APP_KEY: "d37253507ae4d71dee6b"
PUSHER_APP_SECRET: "f564f55c21005e4a443e"
PUSHER_CLUSTER: "ap1"