DB_HOST: "localhost"
DB_PORT: 3306
DB_USER: "root"
DB_PASS: ""
DB_NAME: "sanmateo"
CRYPT_KEY: "vz7oWXaUm691nvAwXJuvs9U6UM04ZZs0"
TOKEN_KEY: "XvkAKPFg6vHQ930PRt13REOZjJuAu0b9fbLaqXC8"
PUSHER_APP_ID: "218537"
PUSHER_APP_KEY: "57c9552505131163078e"
PUSHER_APP_SECRET: "8249101ec755dcf8dc86"
PUSHER_CLUSTER: "ap1"
